"""add_free_qty_and_gst_to_invoice_items

Revision ID: 241f5261c23c
Revises: 9c5374b2a854
Create Date: 2026-06-19 17:13:55.479710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '241f5261c23c'
down_revision: Union[str, None] = '9c5374b2a854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_invoice_items', sa.Column('free_quantity', sa.Integer(), server_default='0', nullable=False))
    op.add_column('purchase_invoice_items', sa.Column('gst', sa.Numeric(precision=10, scale=2), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_invoice_items', 'gst')
    op.drop_column('purchase_invoice_items', 'free_quantity')
    # ### end Alembic commands ###
