"""add_settings_and_customers

Revision ID: 27811ec22368
Revises: 472d459a866c
Create Date: 2026-06-15 09:25:17.018186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '27811ec22368'
down_revision: Union[str, None] = '472d459a866c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('customer_margin', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('doctor_margin', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_agencies_is_deleted'), table_name='agencies', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_batches_is_deleted'), table_name='batches', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_batches_medicine_id'), table_name='batches')
    op.drop_constraint(op.f('uq_medicine_batch'), 'batches', type_='unique')
    op.drop_index(op.f('idx_boxes_deleted_at'), table_name='boxes', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_boxes_shelf_id'), table_name='boxes')
    op.drop_constraint(op.f('uq_shelf_box'), 'boxes', type_='unique')
    op.drop_index(op.f('idx_medicine_categories_is_deleted'), table_name='medicine_categories', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_location_mappings_box_id'), table_name='medicine_location_mappings')
    op.drop_index(op.f('idx_location_mappings_deleted_at'), table_name='medicine_location_mappings', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_medicines_category_id'), table_name='medicines')
    op.drop_index(op.f('idx_medicines_is_deleted'), table_name='medicines', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_purchase_invoice_items_deleted_at'), table_name='purchase_invoice_items', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_purchase_invoice_items_invoice_id'), table_name='purchase_invoice_items')
    op.drop_index(op.f('idx_purchase_invoices_agency_id'), table_name='purchase_invoices')
    op.drop_index(op.f('idx_purchase_invoices_is_deleted'), table_name='purchase_invoices', postgresql_where='(is_deleted = false)')
    op.drop_constraint(op.f('uq_agency_invoice'), 'purchase_invoices', type_='unique')
    op.drop_index(op.f('idx_racks_is_deleted'), table_name='racks', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_roles_is_deleted'), table_name='roles', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_sale_items_deleted_at'), table_name='sale_items', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_sales_deleted_at'), table_name='sales', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_shelves_is_deleted'), table_name='shelves', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_shelves_rack_id'), table_name='shelves')
    op.drop_constraint(op.f('uq_rack_shelf'), 'shelves', type_='unique')
    op.drop_index(op.f('idx_stock_deleted_at'), table_name='stock', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_stock_movements_batch_id'), table_name='stock_movements')
    op.drop_index(op.f('idx_stock_movements_created_at'), table_name='stock_movements')
    op.drop_index(op.f('idx_stock_movements_is_deleted'), table_name='stock_movements', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_stock_movements_medicine_id'), table_name='stock_movements')
    op.drop_index(op.f('idx_users_deleted_at'), table_name='users', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_users_email'), table_name='users', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_users_role_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_users_deleted_at'), 'users', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_stock_movements_medicine_id'), 'stock_movements', ['medicine_id'], unique=False)
    op.create_index(op.f('idx_stock_movements_is_deleted'), 'stock_movements', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_stock_movements_created_at'), 'stock_movements', ['created_at'], unique=False)
    op.create_index(op.f('idx_stock_movements_batch_id'), 'stock_movements', ['batch_id'], unique=False)
    op.create_index(op.f('idx_stock_deleted_at'), 'stock', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_unique_constraint(op.f('uq_rack_shelf'), 'shelves', ['rack_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_shelves_rack_id'), 'shelves', ['rack_id'], unique=False)
    op.create_index(op.f('idx_shelves_is_deleted'), 'shelves', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_sales_deleted_at'), 'sales', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_sale_items_deleted_at'), 'sale_items', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_roles_is_deleted'), 'roles', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_racks_is_deleted'), 'racks', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_unique_constraint(op.f('uq_agency_invoice'), 'purchase_invoices', ['agency_id', 'invoice_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_purchase_invoices_is_deleted'), 'purchase_invoices', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_purchase_invoices_agency_id'), 'purchase_invoices', ['agency_id'], unique=False)
    op.create_index(op.f('idx_purchase_invoice_items_invoice_id'), 'purchase_invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('idx_purchase_invoice_items_deleted_at'), 'purchase_invoice_items', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_medicines_is_deleted'), 'medicines', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_medicines_category_id'), 'medicines', ['category_id'], unique=False)
    op.create_index(op.f('idx_location_mappings_deleted_at'), 'medicine_location_mappings', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_location_mappings_box_id'), 'medicine_location_mappings', ['box_id'], unique=False)
    op.create_index(op.f('idx_medicine_categories_is_deleted'), 'medicine_categories', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_unique_constraint(op.f('uq_shelf_box'), 'boxes', ['shelf_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_boxes_shelf_id'), 'boxes', ['shelf_id'], unique=False)
    op.create_index(op.f('idx_boxes_deleted_at'), 'boxes', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_unique_constraint(op.f('uq_medicine_batch'), 'batches', ['medicine_id', 'batch_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_batches_medicine_id'), 'batches', ['medicine_id'], unique=False)
    op.create_index(op.f('idx_batches_is_deleted'), 'batches', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_agencies_is_deleted'), 'agencies', ['is_deleted'], unique=False, postgresql_where='(is_deleted = false)')
    op.drop_table('system_settings')
    op.drop_table('customers')
    # ### end Alembic commands ###
