"""add_supplier_columns

Revision ID: d392e45ff9cd
Revises: 241f5261c23c
Create Date: 2026-06-23 09:41:46.349028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd392e45ff9cd'
down_revision: Union[str, None] = '241f5261c23c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicine_categories')
    op.add_column('agencies', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('agencies', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('agencies', sa.Column('gst_number', sa.String(length=50), nullable=True))
    op.add_column('agencies', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agencies', 'is_active')
    op.drop_column('agencies', 'gst_number')
    op.drop_column('agencies', 'state')
    op.drop_column('agencies', 'city')
    op.create_table('medicine_categories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('medicine_categories_pkey')),
    sa.UniqueConstraint('name', name=op.f('medicine_categories_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
